#!/bin/sh

if [ ! -e "${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim" ]; then
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi

if [ ! -e $HOME/.rbenv ]; then
  git clone https://github.com/sstephenson/rbenv.git $HOME/.rbenv
fi

if [ ! -e $HOME/.rbenv/plugins/ruby-build ]; then
  git clone https://github.com/sstephenson/ruby-build.git $HOME/.rbenv/plugins/ruby-build
fi

nvim +PlugInstall +PlugClean! +qall
